In [77]:
import pandas as pd

In [78]:
def create_pandas(csv_file):
    return pd.read_csv(csv_file)

In [79]:
dataset = create_pandas('./pisos.csv')

/tmp/ipykernel_37161/970113054.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(csv_file)

In [80]:
dataset.set_index('id', inplace=True)

# DATASET DESCRIPTION

We have tons of data about houses located in Spain. The information we have is: 
+ **summary**: key words for searching in internet
+ **description**: brief description about the place
+ **location**
+ **photo**: url of the photo
+ **recomendado**: categorical variable. Set to "Recomendado" if the home is recomendated
+ **price**
+ **size**
+ **rooms**: number of rooms the house has
+ **price/m2**: relation between the price and the m2
+ **bathroooms**: number of bathrooms
+ **numphotos**
+ **type**
+ **region**

In [81]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 777179 entries, 0 to 831435
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   summary      777179 non-null  object
 1   description  760349 non-null  object
 2   location     776886 non-null  object
 3   photo        776305 non-null  object
 4   recomendado  28241 non-null   object
 5   price        776898 non-null  object
 6   size         776892 non-null  object
 7   rooms        752352 non-null  object
 8   price/m2     744608 non-null  object
 9   bathrooms    752526 non-null  object
 10  Num Photos   776898 non-null  object
 11  type         776898 non-null  object
 12  region       776282 non-null  object
dtypes: object(13)
memory usage: 83.0+ MB

In [82]:
print(dataset.isnull().sum())

summary             0
description     16830
location          293
photo             874
recomendado    748938
price             281
size              287
rooms           24827
price/m2        32571
bathrooms       24653
Num Photos        281
type              281
region            897
dtype: int64

In [83]:
print(dataset.nunique())

summary        151400
description    287749
location        11893
photo          322799
recomendado       227
price           14323
size             2874
rooms             316
price/m2         7508
bathrooms         112
Num Photos        180
type              185
region            904
dtype: int64

In [84]:
print(dataset['recomendado'].unique())

['Recomendado' 'Exclusivo' 'Oportunidad' 'Céntrico' 'Lujo' 'Oferta'
 'Rehabilitado' 'Visítalo' 'Cerca de la playa' 'Primera línea playa'
 'Preciosas vistas' nan 'recomendado' 'Personaliza tu vivienda'
 'Vivenda VPO' 'Próxima construcción' 'Negociable' 'Calidades superiores'
 '135.000 €' '172.000 €' 'Rebajado' 'Urge vender' 'Financiación a medida'
 'Vistas al mar' 'Diseño exclusivo' 'Entrega inmediata' 'Amueblado'
 'Te atendemos online' '80.000 €' 'Urbanización privada' '69.000 €'
 'En construcción' 'Diseña tu casa' 'Últimas viviendas'
 'Financiación 100%' 'Visite piso piloto' '175.000 €' '190.000 €'
 '46.000 €' '165.000 €' 'Alquiler opción compra' '130.000 €' '149.800 €'
 'Llave en mano' '270.000 €' '196.000 €' '140.000 €' '330.000 €'
 '296.690 €' 'Última vivienda' 'Lanzamiento' 'Visite piloto' '68.000 €'
 '19.500 €' '65.000 €' '95.000 €' '195.000 €' '119.000 €' '136.900 €'
 'Pon tú el precio' '71.200 €' 'Oferta SIMA' '200.000 €' '33.000 €'
 '297.000 €' '345.000 €' '134.990 €' 'Oferta SIMED' 'Últimos días'
 '413.000 €' '124.500 €' '174.000 €' '61.500 €' '145.000 €' '780.000 €'
 '60.000 €' '285.000 €' '74.500 €' '55.000 €' '136.300 €' '72.000 €'
 '88.000 €' '155.000 €' '110.000 €' '39.000 €' '49.800 €' '1.000.000 €'
 '1.100.000 €' '107.500 €' '620.000 €' '139.000 €' '115.000 €' '265.000 €'
 '189.000 €' '104.000 €' '89.000 €' '208.000 €' '219.500 €' '59.000 €'
 '107.000 €' '265.900 €' '112.000 €' '113.000 €' '105.000 €' '279.900 €'
 '179.000 €' '247.000 €' '185.000 €' '150.000 €' '260.000 €' '168.000 €'
 '99.000 €' '255.000 €' '390.000 €' '795.000 €' '103.000 €' '76.000 €'
 '215.000 €' '199.000 €' '2.490.000 €' '117.495 €' '875.000 €' '315.000 €'
 '522.000 €' '295.000 €' '729.000 €' '98.000 €' '51.000 €' '293.500 €'
 '174.500 €' '415.000 €' '249.900 €' '125.000 €' '112.400 €' '205.044 €'
 '186.000 €' '2.950.000 €' '1.500.000 €' '267.000 €' '230.000 €'
 '244.000 €' '249.000 €' '174.999 €' '92.260 €' '79.000 €' '310.000 €'
 '167.000 €' '129.000 €' '518.000 €' '266.000 €' '170.000 €' '309.000 €'
 '325.000 €' '276.000 €' '142.900 €' '120.000 €' '139.900 €' '245.000 €'
 '850.000 €' '250.000 €' '222.664 €' '138.000 €' '99.990 €' '220.000 €'
 '156.000 €' '1.300.000 €' '239.000 €' '105.800 €' '176.979 €' '240.000 €'
 '529.900 €' '133.000 €' '101.000 €' '158.000 €' '349.000 €' '1.235.000 €'
 '461.200 €' '159.000 €' '399.000 €' '139.500 €' '149.900 €' '82.900 €'
 '214.000 €' '90.000 €' '246.000 €' '147.000 €' '269.000 €' '259.000 €'
 '675.000 €' '990.000 €' '75.000 €' '67.000 €' '166.000 €' '53.800 €'
 '750.000 €' '564.100 €' '470.000 €' '85.000 €' '223.523 €' '109.000 €'
 '152.999 €' '123.000 €' '159.999 €' '199.999 €' '350.000 €' '144.999 €'
 '114.000 €' '47.000 €' '149.999 €' '160.000 €' '83.000 €' 'A consultar'
 '235.000 €' '420.000 €' '180.000 €' '87.980 €' '48.700 €' '153.999 €'
 '72.499 €' '224.999 €' '121.999 €' '92.999 €' '172.999 €' '520.000 €'
 '224.500 €' '632.000 €' '178.000 €' '367.300 €']

In [88]:
wrong_items = list()

for i, j, z in zip(dataset['recomendado'], dataset['price'], dataset.index):
    if str(i)[-1] == '€':
        wrong_items.append(z)

dataset = dataset[~dataset.index.isin(wrong_items)]

In [91]:
dataset['location'].isnull().sum()

293

In [92]:
dataset = dataset.dropna(subset=['location'])
dataset['location'].isnull().sum()

0

In [93]:
dataset

,summary,description,location,photo,recomendado,price,size,rooms,price/m2,bathrooms,Num Photos,type,region
id,,,,,,,,,,,,,
0,Casa en calle Urb. Las Mimosas,NaN,Ames (San Tome),https://fotos4.imghs.net/nrd/1069/104/1069_I00...,Recomendado,250.000 €,315 m²,4,793 €/m²,3,31,pisos,a_coruna
1,Piso en Milladoiro,NaN,Ames (San Tome),https://fotos4.imghs.net/nrd/1069/113/1069_I00...,Recomendado,90.000 €,72 m²,2,1.250 €/m²,1,11,pisos,a_coruna
2,Casa en calle La Piedra,NaN,A Ortigueira (Cariño),https://fotos1.imghs.net/nrd//999170/892070610...,Recomendado,50.000 €,92 m²,2,543 €/m²,1,40,pisos,a_coruna
3,Casa en Perillo,NaN,Perillo (Oleiros),https://fotos3.imghs.net/nrd/1089/198/1089_XA2...,Recomendado,359.000 €,244 m²,4,1.471 €/m²,3,39,pisos,a_coruna
4,Chalet en Urbanización Las Mimosas,NaN,O Milladoiro (Ames),https://fotos5.imghs.net/nrd/1097/754/1097_0_f...,Recomendado,200.430 €,315 m²,4,636 €/m²,3,24,pisos,a_coruna
...,...,...,...,...,...,...,...,...,...,...,...,...,...
831430,Finca rústica en Cardedeu,Suelo urbano no consolidado de uso residencial...,Cardedeu,https://fotos4.imghs.net/nrd/1088/335/1088_727...,NaN,A consultar,4.381 m²,NaN,NaN,NaN,10,fincas_rusticas,valles_oriental_sud
831431,Finca rústica en Granollers,Solar urbano consolidado sin edificación de us...,Can Bassa-Palou (Granollers),https://fotos2.imghs.net/nrd/1088/137/1088_727...,NaN,A consultar,4.063 m²,NaN,NaN,NaN,4,fincas_rusticas,valles_oriental_sud
831432,Finca rústica en La Roca del Vallès,+finca situada al norte del municipio de la ro...,La Roca del Vallès,https://fotos3.imghs.net/nrd//1005/057/1005_60...,NaN,1.350.000 €,350 m²,5,3.857 €/m²,2.0,9,fincas_rusticas,valles_oriental_sud
831433,"Finca rústica en Bajada Les Valls, nº S/N","""Masía típica catalana, casa principal de 165 ...",La Roca del Vallès,https://fotos5.imghs.net/nrd/1098/460/1098_0_f...,NaN,456.000 €,202 m²,5,2.257 €/m²,3.0,30,fincas_rusticas,valles_oriental_sud
831435,Loft en calle Catlunya,Immoàtic - ¿Cansado de la vivienda tradicional...,Llerona (Les Franqueses del Vallès),https://fotos2.imghs.net/nrd//512120/171673332...,NaN,155.000 €,87 m²,1,1.781 €/m²,1.0,34,lofts,valles_oriental_sud